# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MeiTu")
        MainWindow.resize(800, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbCamera = QtWidgets.QLabel(self.centralwidget)
        self.lbCamera.setGeometry(QtCore.QRect(50, 120, 180, 180))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(13)
        self.lbCamera.setFont(font)
        self.lbCamera.setTextFormat(QtCore.Qt.AutoText)
        self.lbCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCamera.setObjectName("lbCamera")
        self.btnOpenCamera = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenCamera.setGeometry(QtCore.QRect(50, 350, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.btnOpenCamera.setFont(font)
        self.btnOpenCamera.setObjectName("btnOpenCamera")
        self.lbImageGrabbed = QtWidgets.QLabel(self.centralwidget)
        self.lbImageGrabbed.setGeometry(QtCore.QRect(300, 120, 180, 180))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(13)
        self.lbImageGrabbed.setFont(font)
        self.lbImageGrabbed.setTextFormat(QtCore.Qt.AutoText)
        self.lbImageGrabbed.setAlignment(QtCore.Qt.AlignCenter)
        self.lbImageGrabbed.setObjectName("lbImageGrabbed")
        self.btnGrabImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnGrabImage.setGeometry(QtCore.QRect(50, 420, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.btnGrabImage.setFont(font)
        self.btnGrabImage.setObjectName("btnGrabImage")
        self.lbBeautyImage = QtWidgets.QLabel(self.centralwidget)
        self.lbBeautyImage.setGeometry(QtCore.QRect(530, 120, 180, 180))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(13)
        self.lbBeautyImage.setFont(font)
        self.lbBeautyImage.setTextFormat(QtCore.Qt.AutoText)
        self.lbBeautyImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbBeautyImage.setObjectName("lbBeautyImage")
        self.btnGray = QtWidgets.QPushButton(self.centralwidget)
        self.btnGray.setGeometry(QtCore.QRect(290, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.btnGray.setFont(font)
        self.btnGray.setObjectName("btnGray")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 350, 20, 111))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnSmooth = QtWidgets.QPushButton(self.centralwidget)
        self.btnSmooth.setGeometry(QtCore.QRect(290, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.btnSmooth.setFont(font)
        self.btnSmooth.setObjectName("btnSmooth")
        self.btnLargeEyes = QtWidgets.QPushButton(self.centralwidget)
        self.btnLargeEyes.setGeometry(QtCore.QRect(440, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.btnLargeEyes.setFont(font)
        self.btnLargeEyes.setObjectName("btnLargeEyes")
        self.btnSmallFace = QtWidgets.QPushButton(self.centralwidget)
        self.btnSmallFace.setGeometry(QtCore.QRect(440, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.btnSmallFace.setFont(font)
        self.btnSmallFace.setObjectName("btnSmallFace")
        self.btnContour = QtWidgets.QPushButton(self.centralwidget)
        self.btnContour.setGeometry(QtCore.QRect(590, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.btnContour.setFont(font)
        self.btnContour.setObjectName("btnContour")
        self.btnThreshold = QtWidgets.QPushButton(self.centralwidget)
        self.btnThreshold.setGeometry(QtCore.QRect(590, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.btnThreshold.setFont(font)
        self.btnThreshold.setObjectName("btnThreshold")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(250, 130, 20, 161))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnOpenCamera.clicked.connect(MainWindow.open_camera)
        self.btnGrabImage.clicked.connect(MainWindow.grab_image)
        self.btnGray.clicked.connect(MainWindow.gray)
        self.btnSmooth.clicked.connect(MainWindow.smooth)
        self.btnLargeEyes.clicked.connect(MainWindow.large_eyes)
        self.btnSmallFace.clicked.connect(MainWindow.small_face)
        self.btnContour.clicked.connect(MainWindow.contour)
        self.btnThreshold.clicked.connect(MainWindow.threshold)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbCamera.setText(_translate("MainWindow", "Camera Area"))
        self.btnOpenCamera.setText(_translate("MainWindow", "Open Camera"))
        self.lbImageGrabbed.setText(_translate("MainWindow", "Image Grabbed"))
        self.btnGrabImage.setText(_translate("MainWindow", "Grab Image"))
        self.lbBeautyImage.setText(_translate("MainWindow", "Beauty Image"))
        self.btnGray.setText(_translate("MainWindow", "Gray"))
        self.btnSmooth.setText(_translate("MainWindow", "Smooth"))
        self.btnLargeEyes.setText(_translate("MainWindow", "Large Eyes"))
        self.btnSmallFace.setText(_translate("MainWindow", "Detect Face"))
        self.btnContour.setText(_translate("MainWindow", "Particle"))
        self.btnThreshold.setText(_translate("MainWindow", "Cartoon"))
        self.label.setText(_translate("MainWindow", "Magic Effect v1.0"))

